#!/bin/bash

# Pick a docker container from list and stop and remove it

set -e

source picker.sh


ddestroy() {
  picker .destroythis, ID

  local COMMAND="docker stop $ID && docker rm $ID"

  eval $COMMAND
}

ddestroy

